### ISSUE TITLE
No Video played

### ISSUE THREAD

**Issue by ar84** [PtrBld/MMM-Button#5]
Hello
The button is pressed and also realized that it was pressed but no video is played. Only the following error message occurs

0|mm       | ReferenceError: socketNotificationReceived is not defined
0|mm       |     at Timeout._onTimeout (/home/pi/MagicMirror/modules/MMM-Podcast/node_helper.js:32:27)
0|mm       |     at ontimeout (timers.js:365:14)
0|mm       |     at tryOnTimeout (timers.js:237:5)
0|mm       |     at Timer.listOnTimeout (timers.js:207:5)

Hope for help.

Best regards

**Comment by ar84** [comment]
sorry wrong module
